
package ReservationSystem;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * The AdminLogin class provides the login interface for admin users.
 * It connects to the database to verify the admin's credentials.
 */
public class AdminLogin extends javax.swing.JFrame {
    Connection con = null; 
    ResultSet rs = null;
    PreparedStatement pst = null;
    private boolean isPasswordVisible = false;   
    
    /**
     * Creates new form AdminLogin and initializes components.
     */    
    public AdminLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        con = Db.mycon();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        adminNumberLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        password = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        loginLabel = new javax.swing.JLabel();
        adminLabel = new javax.swing.JLabel();
        mainButton = new javax.swing.JButton();
        showPassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(125, 10, 10));

        title1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        title1.setForeground(new java.awt.Color(254, 221, 11));
        title1.setText("SCHOOL ROOM");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/splashlogo.png"))); // NOI18N

        title2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        title2.setForeground(new java.awt.Color(254, 221, 11));
        title2.setText("RESERVATION ");

        title4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        title4.setForeground(new java.awt.Color(254, 221, 11));
        title4.setText("SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(title4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(title1)
                            .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(logo)
                        .addGap(60, 60, 60))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title4)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 174, 69));

        adminNumberLabel.setText("Admin Number:");

        passwordLabel.setText("Password:");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        password.setBackground(new java.awt.Color(255, 174, 69));
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        loginButton.setBackground(new java.awt.Color(153, 255, 153));
        loginButton.setText("LOGIN");
        loginButton.setBorder(null);
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginButtonKeyPressed(evt);
            }
        });

        username.setBackground(new java.awt.Color(255, 174, 69));
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        username.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        loginLabel.setBackground(new java.awt.Color(125, 10, 10));
        loginLabel.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(125, 10, 10));
        loginLabel.setText("LOGIN");

        adminLabel.setText("Not an Admin?");

        mainButton.setBackground(new java.awt.Color(255, 174, 69));
        mainButton.setForeground(new java.awt.Color(0, 0, 51));
        mainButton.setText("Back to Main");
        mainButton.setBorder(null);
        mainButton.setBorderPainted(false);
        mainButton.setContentAreaFilled(false);
        mainButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButtonActionPerformed(evt);
            }
        });

        showPassword.setBackground(new java.awt.Color(255, 174, 69));
        showPassword.setForeground(new java.awt.Color(0, 0, 51));
        showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/show.png"))); // NOI18N
        showPassword.setBorder(null);
        showPassword.setBorderPainted(false);
        showPassword.setContentAreaFilled(false);
        showPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(adminNumberLabel))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(username, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(adminLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mainButton))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2)
                                    .addComponent(password)
                                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(showPassword)))))
                .addGap(54, 54, 54))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(loginLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(loginLabel)
                .addGap(31, 31, 31)
                .addComponent(adminNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminLabel)
                    .addComponent(mainButton))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Authenticates the admin user based on the entered username and password.
    */   
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        String uN = username.getText();
        String pS = String.valueOf(password.getPassword());
        if (uN.trim().equals("")){
            jOptionPane1.showMessageDialog(rootPane, "Enter your username to Login", "Empty Username", 2);
        } else if (pS.trim().equals("")) {
            jOptionPane1.showMessageDialog(rootPane, "Enter your password to Login", "Empty Password", 2);
        } else {
            try {
                
                String sql = "SELECT * FROM admin WHERE admin = ? AND password = ?";
                pst = con.prepareCall(sql);
                pst.setString(1, uN);
                pst.setString(2, pS);
                
                rs = pst.executeQuery();

                if (rs.next()) {
                    User user = new User(uN);
                    AdminHomePage homePageFrame = new AdminHomePage(user, this);
                    homePageFrame.setVisible(true);
                    homePageFrame.pack();
                    homePageFrame.setLocationRelativeTo(null);
                    this.dispose();                
                    
                } else {
                    jOptionPane1.showMessageDialog(rootPane, "Wrong Username or Password", "Login Failed!", 2);
                }
            } catch (Exception e) {
                e.printStackTrace(); // Add proper error handling here
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * This method handles the key press event on the "Login" button.
     * It checks if the pressed key is Enter (VK_ENTER). If yes, it retrieves the username from the `username` text field and the password from the `password` password field.
     * It then attempts to connect to the database and execute a prepared statement to check for a matching admin record with the provided username and password.
     * - If a match is found, a new `User` object is created with the username and a new `AdminHomePage` frame is opened, passing the user and a reference to this frame. The new frame is made visible, packed, centered, and this frame is hidden.
     * - If no match is found, a login failed message is displayed using a JOptionPane dialog.
     * In case of any exceptions during the process, it catches the exception but doesn't perform any specific action (consider adding logging or error handling as needed).
     *
     * @param evt The `KeyEvent` object generated by the key press on the button.
     */
    private void loginButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String uN = username.getText();
            String pS = String.valueOf(password.getPassword());

            try {
                String sql = " SELECT * FROM admin WHERE admin = ? AND password = ?";
                pst = con.prepareCall(sql);
                pst.setString(1, uN);
                pst.setString(2, pS);

                rs = pst.executeQuery();

                if (rs.next()) {
                    User user = new User(uN);
                    AdminHomePage homePageFrame = new AdminHomePage(user, this);
                    homePageFrame.setVisible(true);
                    homePageFrame.pack();
                    homePageFrame.setLocationRelativeTo(null);
                    this.setVisible(false);   
                } else {
                    jOptionPane1.showMessageDialog(rootPane, "Login Failed!");
                }
            } catch (HeadlessException | SQLException e){

            }
        }
    }//GEN-LAST:event_loginButtonKeyPressed

    /**
     * This method handles the action event triggered when the "Main Page" button is clicked.
     * It creates a new instance of the `MainPage` class, sets its visibility to true, packs and centers the frame on the screen, and then disposes of the current frame.
     *
     * @param evt The `ActionEvent` object generated by the button click.
     */
    private void mainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButtonActionPerformed

        MainPage mainFrame = new MainPage ();

        mainFrame.setVisible(true);
        mainFrame.pack();
        mainFrame.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_mainButtonActionPerformed
    /**
     * This method handles the action event triggered when the "Show Password" checkbox is clicked.
     * It toggles the visibility of the password characters in the `password` field.
     * - If the checkbox is checked (selected), the password field's echo character is set to a bullet point ('•') to hide the password.
     * - If the checkbox is unchecked (deselected), the password field's echo character is set to null ((char) 0) to show the password characters.
     * The `isPasswordVisible` boolean flag is updated to reflect the current state.
     *
     * @param evt The `ActionEvent` object generated by the checkbox click.
     */
    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        if (isPasswordVisible) {
            password.setEchoChar('•'); // Hide password
        } else {
            password.setEchoChar((char) 0); // Show password
        }
        isPasswordVisible = !isPasswordVisible;
    }//GEN-LAST:event_showPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLabel;
    private javax.swing.JLabel adminNumberLabel;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel logo;
    private javax.swing.JButton mainButton;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton showPassword;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title4;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
