package ReservationSystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 * Register class represents the Register window of the application.
 * It allows users to register for an account by entering their information
 * and creating a password.
 */
public class Register extends javax.swing.JFrame {
    
    Connection con = null; 
    ResultSet rs = null;
    PreparedStatement pst = null;
    private boolean isPasswordVisible = false;    
    /**
     * Creates a new Register form and centers it on the screen.
     * Also establishes a connection to the database (implementation not shown).
     */   
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
        con = Db.mycon();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jOptionPane2 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        firstnameLabel = new javax.swing.JLabel();
        confirmPasswordLabel = new javax.swing.JLabel();
        confirmPassword = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        studNo = new javax.swing.JTextField();
        registerLabel = new javax.swing.JLabel();
        middleNameLabel = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        yrsec = new javax.swing.JTextField();
        yrsecLabel = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        studLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        showConfirmPassword = new javax.swing.JButton();
        showPassword1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(125, 10, 10));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        title1.setForeground(new java.awt.Color(254, 221, 11));
        title1.setText("SCHOOL ROOM");
        jPanel2.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 306, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/splashlogo.png"))); // NOI18N
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 101, -1, -1));

        title2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        title2.setForeground(new java.awt.Color(254, 221, 11));
        title2.setText("RESERVATION ");
        jPanel2.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 347, -1, -1));

        title3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        title3.setForeground(new java.awt.Color(254, 221, 11));
        title3.setText("SYSTEM");
        jPanel2.add(title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 388, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 174, 69));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstnameLabel.setText("First name:");
        jPanel3.add(firstnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        confirmPasswordLabel.setText("Confirm Password:");
        jPanel3.add(confirmPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        confirmPassword.setBackground(new java.awt.Color(255, 174, 69));
        confirmPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 288, 33));

        registerButton.setBackground(new java.awt.Color(153, 255, 153));
        registerButton.setText("REGISTER");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        registerButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                registerButtonKeyPressed(evt);
            }
        });
        jPanel3.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 288, -1));

        studNo.setBackground(new java.awt.Color(255, 174, 69));
        studNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        studNo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel3.add(studNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 288, 34));

        registerLabel.setBackground(new java.awt.Color(125, 10, 10));
        registerLabel.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(125, 10, 10));
        registerLabel.setText("REGISTER");
        jPanel3.add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 6, -1, -1));

        middleNameLabel.setText("Middle name:");
        jPanel3.add(middleNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        lname.setBackground(new java.awt.Color(255, 174, 69));
        lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lname.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel3.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 288, 34));

        lastNameLabel.setText("Last name:");
        jPanel3.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        mname.setBackground(new java.awt.Color(255, 174, 69));
        mname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mname.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel3.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 288, 34));

        yrsec.setBackground(new java.awt.Color(255, 174, 69));
        yrsec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        yrsec.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel3.add(yrsec, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 288, 34));

        yrsecLabel.setText("Year and section:");
        jPanel3.add(yrsecLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        email.setBackground(new java.awt.Color(255, 174, 69));
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        email.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 288, 34));

        emailLabel.setText("Email:");
        jPanel3.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        fname.setBackground(new java.awt.Color(255, 174, 69));
        fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fname.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel3.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 288, 34));

        studLabel.setText("Student Number:");
        jPanel3.add(studLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        loginButton.setBackground(new java.awt.Color(255, 174, 69));
        loginButton.setForeground(new java.awt.Color(0, 0, 255));
        loginButton.setText("Back to login");
        loginButton.setBorder(null);
        loginButton.setContentAreaFilled(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel3.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        password.setBackground(new java.awt.Color(255, 174, 69));
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 288, 33));

        passwordLabel.setText("Password:");
        jPanel3.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        showConfirmPassword.setBackground(new java.awt.Color(255, 174, 69));
        showConfirmPassword.setForeground(new java.awt.Color(0, 0, 51));
        showConfirmPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/show.png"))); // NOI18N
        showConfirmPassword.setBorder(null);
        showConfirmPassword.setBorderPainted(false);
        showConfirmPassword.setContentAreaFilled(false);
        showConfirmPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showConfirmPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(showConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 40, -1));

        showPassword1.setBackground(new java.awt.Color(255, 174, 69));
        showPassword1.setForeground(new java.awt.Color(0, 0, 51));
        showPassword1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/show.png"))); // NOI18N
        showPassword1.setBorder(null);
        showPassword1.setBorderPainted(false);
        showPassword1.setContentAreaFilled(false);
        showPassword1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassword1ActionPerformed(evt);
            }
        });
        jPanel3.add(showPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 40, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   /**
     * This method is called when the register button is clicked.
     * It validates user input, registers the user in the database, and displays success/error messages.
     * 
     * @param evt the ActionEvent object
     */
    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
               
        String ps, query;
        String fn, ln, mn, ys, em, sno;
        
        try {
            Statement st = con.createStatement();
                    
            if ("".equals(studNo.getText())){
                jOptionPane1.showMessageDialog(this, "Student Number is required");
            } else if (!isValidStudentNumber(studNo.getText())) {
                 jOptionPane1.showMessageDialog(rootPane, "Invalid student number format!", "Invalid",jOptionPane1.ERROR_MESSAGE);                       
            } else if ("".equals(fname.getText())){
                jOptionPane1.showMessageDialog(this, "First Name is required");
            } else if (!isValidName(fname.getText())) {
                jOptionPane1.showMessageDialog(rootPane, "Invalid name format!", "Invalid", jOptionPane1.ERROR_MESSAGE);                  
            } else if ("".equals(mname.getText())){
                jOptionPane1.showMessageDialog(this, "Middle Name is required");   
            } else if (!isValidName(mname.getText())) {
                jOptionPane1.showMessageDialog(rootPane, "Invalid name format!", "Invalid", jOptionPane1.ERROR_MESSAGE);                    
            } else if ("".equals(lname.getText())){
                jOptionPane1.showMessageDialog(this, "Last Name is required");         
            } else if (!isValidName(lname.getText())) {
                jOptionPane1.showMessageDialog(rootPane, "Invalid name format!", "Invalid", jOptionPane1.ERROR_MESSAGE);                   
            } else if ("".equals(yrsec.getText())){
                jOptionPane1.showMessageDialog(this, "Year and Section is required");                
            } else if (!isValidEmail(email.getText())) {
                jOptionPane1.showMessageDialog(rootPane, "Invalid email format!", "Invalid", jOptionPane1.ERROR_MESSAGE);  
            } else if ("".equals(password.getText())){
                jOptionPane1.showMessageDialog(this, "Password is required"); 
            } else if ("".equals(confirmPassword.getText())){
                jOptionPane1.showMessageDialog(this, "Confirm Password is required"); 
            } else if (!password.getText().equals(confirmPassword.getText())){
                jOptionPane1.showMessageDialog(this, "Password do not match! Please re-enter password.", "Error", jOptionPane1.ERROR_MESSAGE); 
            } else {
                sno = studNo.getText();
                fn = fname.getText();
                ln = lname.getText();
                mn = mname.getText();
                ys = yrsec.getText();
                em = email.getText();
                ps = password.getText();                
                
                query = "INSERT INTO tblstudent (studno, firstname, lastname, middlename, yrsec, email, password) "
                       + "VALUES ('"+sno+ "','"+fn+"','"+mn+"','"+ln+"','"+ys+"','"+em+"','"+ps+"')";  
                
                st.executeUpdate(query);
                studNo.setText("");
                fname.setText("");
                mname.setText("");
                lname.setText("");
                yrsec.setText("");
                email.setText("");
                password.setText("");  
                confirmPassword.setText("");                
                
                jOptionPane2.showMessageDialog(this, "Successfully Registered");
                MainLogin MainLoginFrame = new MainLogin ();

                MainLoginFrame.setVisible(true);
                MainLoginFrame.pack();
                MainLoginFrame.setLocationRelativeTo(null);                
                this.dispose();          
                con.close();
            }               
                    
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
            jOptionPane2.showMessageDialog(this, "Student Number already exists! Please try again.","Duplicate Entry", jOptionPane2.ERROR_MESSAGE);
           
        }      
          
    }//GEN-LAST:event_registerButtonActionPerformed

    private void registerButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerButtonKeyPressed

    }//GEN-LAST:event_registerButtonKeyPressed
    /**
     * This method is called when the login button is pressed.
     * It creates and displays the MainLogin frame and disposes of the current frame.
     *
     * @param evt the ActionEvent triggered by pressing the login button
     */
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        MainLogin MainLoginFrame = new MainLogin();

        MainLoginFrame.setVisible(true);
        MainLoginFrame.pack();
        MainLoginFrame.setLocationRelativeTo(null);
        this.dispose();        
    }//GEN-LAST:event_loginButtonActionPerformed
    /**
     * This method is called when the show/hide confirm password button is pressed.
     * It toggles the visibility of the confirm password field.
     *
     * @param evt the ActionEvent triggered by pressing the show/hide confirm password button
     */
    private void showConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showConfirmPasswordActionPerformed
        if (isPasswordVisible) {
            confirmPassword.setEchoChar('•'); // Hide password
            showConfirmPassword.setText("Show Password");
        } else {
            confirmPassword.setEchoChar((char) 0); // Show password
            showConfirmPassword.setText("Hide Password");
        }
        isPasswordVisible = !isPasswordVisible;             
    }//GEN-LAST:event_showConfirmPasswordActionPerformed
    /**
     * This method is called when the show/hide password button is pressed.
     * It toggles the visibility of the password field.
     *
     * @param evt the ActionEvent triggered by pressing the show/hide confirm password button
     */
    private void showPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassword1ActionPerformed
        if (isPasswordVisible) {
            password.setEchoChar('•'); // Hide password
            showPassword1.setText("Show Password");
        } else {
            password.setEchoChar((char) 0); // Show password
            showPassword1.setText("Hide Password");
        }
        isPasswordVisible = !isPasswordVisible;   
    }//GEN-LAST:event_showPassword1ActionPerformed

    public boolean isValidEmail(String email) {
        String regex = "^(.+)@(.+).com$";
        return email.matches(regex);
    } 

    public boolean isValidStudentNumber(String studentNumber) {
        // Define the regex pattern for the student number format
        String regex = "^2\\d{3}-\\d{5}-TG-0$";
        return studentNumber.matches(regex);
    }
    
    public boolean isValidName(String name) {
        // Define the regex pattern to allow letters, spaces, periods, and hyphens
        String regex = "^[a-zA-Z.\\s-]+$";
        return name.matches(regex);
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField fname;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lname;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.JTextField mname;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JButton showConfirmPassword;
    private javax.swing.JButton showPassword1;
    private javax.swing.JLabel studLabel;
    private javax.swing.JTextField studNo;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JTextField yrsec;
    private javax.swing.JLabel yrsecLabel;
    // End of variables declaration//GEN-END:variables
}
